name: Actions workflow

on: [push, pull_request]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Lists files
        run: |
          pwd
          ls
      - name: checkout
        uses: actions/checkout@v1
      - name: Lists files after checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        # git clone git@github:$GITHUB_REPOSITORY
        # git checkout $GITHUB_SHA
      - name: Simple JS Actionsnow
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Sree
      - name: Log Greetings time
        run: echo "${{ steps.greet.outputs.time }}"
  # Push a commit using the built-in token:: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
