name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello world"
      - name: Multistring Commands
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: Bash Command
        run: |
          pwd
          ls
        shell: bash
  run-windows-command:
    runs-on: windows-latest
    needs: [run-windows-command]
    steps:
      - name: Directory powershell
        run: get-location
      - name: Bash Command
        run: pwd
        shell: bash
        
