name: Shell Command

on: [push]

jobs:
    run-sehll-command: 
      runs-on: ubuntu-latest
      needs: [run-windows-command]
      steps:
        - name: echo a string
          run: echo "hello world sudhakar"
        - name: multiline script
          run: |
            node -v
            npm -v
        - name: python Command
          run: |
            import platform
            print(platform.processor())
          shell: python
    run-windows-command:
      runs-on: windows-latest
      ## needs: [run-sehll-command]
      steps:
        - name: Directory
            Powershell
          run: Get-location
        - name: Directory Bash
          run: pwd
          shell: bash


